### ISSUE TITLE
Build failed when using typescript.

### ISSUE THREAD

**Issue by raihan-brain** [AfzalSabbir/vue-sfc-vite#8]
When building a package with typescript getting this error.
```
Could not resolve entry module (src/components/index.js).
error during build:
Error: Could not resolve entry module (src/components/index.js).
    at error (file:///Users/raihanzaman/Desktop/TEQ_VP/reusable/vue3/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.loadEntryModule (file:///Users/raihanzaman/Desktop/TEQ_VP/reusable/vue3/node_modules/rollup/dist/es/shared/rollup.js:22175:20)
    at async Promise.all (index 0)
```

When looking at the vite.confog.ts file I found that 
```
  lib: {
      // Could also be a dictionary or array of multiple entry points
      entry: resolve(__dirname, "src/components/index.js"),
      name: "BaseSidebar",
      // the proper extensions will be added
      fileName: (format) => `base-sidebar.${format}.js`,
    },
```

This should have been  "src/components/index.ts" for anyone who has chosen typescript for making a library.

**Comment by ARBS23** [comment]
@raihan-brain Thank you for the issue. Already fixed [@afzalsabbir/vue-sfc-vite@0.1.0-alpha-0](https://github.com/AfzalSabbir/vue-sfc-vite/pkgs/npm/vue-sfc-vite/65673022).
